### ISSUE TITLE
Unhandled error when owoifying "NIDORINO"

### ISSUE THREAD

**Issue by luctowers** [deadshot465/owoify.py#1] opened 2021-03-15 07:48 UTC
```
>>> owoify("NIDORINO")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/luctowers/.local/lib/python3.8/site-packages/owoify/owoify.py", line 42, in owoify
    words = list(map(lambda w: map_owoify_levels(w, level), words))
  File "/home/luctowers/.local/lib/python3.8/site-packages/owoify/owoify.py", line 42, in <lambda>
    words = list(map(lambda w: map_owoify_levels(w, level), words))
  File "/home/luctowers/.local/lib/python3.8/site-packages/owoify/owoify.py", line 17, in map_owoify_levels
    word = func(word)
  File "/home/luctowers/.local/lib/python3.8/site-packages/owoify/utility/mapping.py", line 199, in map_specific_consonants_o_to_letter_and_wo
    input = input.replace_with_func_multiple(SPECIFIC_CONSONANTS_O_TO_LETTER_AND_WO_UPPER, mapping_function_1)
  File "/home/luctowers/.local/lib/python3.8/site-packages/owoify/structures/word.py", line 74, in replace_with_func_multiple
    replaced_words = list(map(lambda s: s.replace(s, replace_value), collection))
  File "/home/luctowers/.local/lib/python3.8/site-packages/owoify/structures/word.py", line 74, in <lambda>
    replaced_words = list(map(lambda s: s.replace(s, replace_value), collection))
AttributeError: 'tuple' object has no attribute 'replace'
```

**Comment by deadshot465** [comment] 2021-03-27 09:32
Hi, sorry for the late reply because for some reason GitHub didn't notify me about the new issue. I have reproduced this error and will look into it now. Thanks for the report!

**Comment by deadshot465** [comment] 2021-03-27 10:47
The error has been fixed in the latest version. Thank you very much!
I'll close the issue for now, but if you find other errors/exceptions or it still doesn't work, please feel free to report it again!

**Closed as completed by deadshot465** 2021-03-27 10:47 UTC
